const hamburger=document.getElementById('hamburger');
const navLinks=document.getElementById('navLinks');
hamburger.addEventListener('click',()=>{navLinks.classList.toggle('active')});
document.querySelectorAll('.nav-links a').forEach(link=>{link.addEventListener('click',()=>{navLinks.classList.remove('active')})});
document.querySelectorAll('.faq-question').forEach(button=>{button.addEventListener('click',()=>{const answer=button.nextElementSibling;const icon=button.querySelector('.faq-icon');document.querySelectorAll('.faq-answer').forEach(item=>{if(item!==answer&&item.classList.contains('active')){item.classList.remove('active');item.previousElementSibling.querySelector('.faq-icon').textContent='+'}});answer.classList.toggle('active');icon.textContent=answer.classList.contains('active')?'−':'+'})});
window.addEventListener('scroll',()=>{const navbar=document.getElementById('navbar');if(window.scrollY>50){navbar.style.background='rgba(11,31,58,.98)';navbar.style.boxShadow='0 2px 10px rgba(0,0,0,.3)'}else{navbar.style.background='rgba(11,31,58,.95)';navbar.style.boxShadow='none'}});
const contactForm=document.getElementById('contactForm');
if(contactForm){contactForm.addEventListener('submit',function(e){e.preventDefault();const name=document.getElementById('name').value;const email=document.getElementById('email').value;const service=document.getElementById('service').value;const message=document.getElementById('message').value;const mailtoLink='mailto:contact@aungbobokyaw.com?subject='+encodeURIComponent('Service Request from '+name)+'&body='+encodeURIComponent('Name: '+name+'\nEmail: '+email+'\nService: '+service+'\n\nMessage:\n'+message);window.location.href=mailtoLink;this.reset();alert('Thank you! Your email client will open to send your message.')})}
const translations={
en:{home:'Home',services:'Services',solutions:'Solutions',ai:'AI',projects:'Projects',pricing:'Pricing',about:'About',contact:'Contact',blog:'Blog',heroTitle:'Build Faster.<br>Create Smarter.',heroDesc:'neXa brings AI, web development, automation, cloud solutions, and digital services together in one modern technology ecosystem.',exploreNeXa:'Explore neXa',getInTouch:'Get in Touch',servicesTitle:'Everything You Need to Build Digitally',servicesDesc:'From websites and AI systems to automation and cloud solutions, neXa provides practical technology services designed for modern businesses and creators.'},
mm:{home:'ပင်မ',services:'ဝန်ဆောင်မှုများ',solutions:'ဖြေရှင်းနည်းများ',ai:'AI',projects:'ပရောဂျက်များ',pricing:'ဈေးနှုန်းများ',about:'အကြောင်း',contact:'ဆက်သွယ်ရန်',blog:'ဘလော့',heroTitle:'မြန်မြန်တည်ဆောက်ပါ။<br>ထက်မြက်စွာ ဖန်တီးပါ။',heroDesc:'neXa သည် AI၊ ဝဘ်ဖွံ့ဖြိုးတိုးတက်မှု၊ အလိုအလျောက်လုပ်ဆောင်မှု၊ cloud ဖြေရှင်းနည်းများနှင့် ဒစ်ဂျစ်တယ်ဝန်ဆောင်မှုများကို တစ်နေရာတည်းမှာ ပေါင်းစပ်ပေးပါသည်။',exploreNeXa:'neXa ကို စူးစမ်းပါ',getInTouch:'ဆက်သွယ်ပါ',servicesTitle:'ဒစ်ဂျစ်တယ် တည်ဆောက်ရန် လိုအပ်သမျှ',servicesDesc:'ဝဘ်ဆိုဒ်များ၊ AI စနစ်များ၊ အလိုအလျောက်လုပ်ဆောင်မှုနှင့် cloud ဖြေရှင်းနည်းများအထိ neXa သည် ခေတ်မီစီးပွားရေးလုပ်ငန်းများအတွက် လက်တွေ့ကျသော နည်းပညာဝန်ဆောင်မှုများကို ပေးပါသည်.'}
};
let currentLang='en';
const langToggle=document.getElementById('langToggle');
if(langToggle){langToggle.addEventListener('click',()=>{if(currentLang==='en'){currentLang='mm';langToggle.textContent='MM | EN'}else{currentLang='en';langToggle.textContent='EN | MM'}applyLanguage(currentLang)})}
function applyLanguage(lang){const t=translations[lang];if(!t)return;document.querySelectorAll('.nav-links a').forEach(link=>{const text=link.textContent.trim();if(text==='Home')link.textContent=t.home;if(text==='Services')link.textContent=t.services;if(text==='Solutions')link.textContent=t.solutions;if(text==='AI')link.textContent=t.ai;if(text==='Projects')link.textContent=t.projects;if(text==='Pricing')link.textContent=t.pricing;if(text==='About')link.textContent=t.about;if(text==='Contact')link.textContent=t.contact;if(text==='Blog')link.textContent=t.blog});document.querySelector('.hero h1').innerHTML=t.heroTitle;document.querySelector('.hero-description').textContent=t.heroDesc;document.querySelectorAll('.hero-buttons .btn-primary').forEach(btn=>{btn.textContent=t.exploreNeXa});document.querySelectorAll('.hero-buttons .btn-secondary').forEach(btn=>{btn.textContent=t.getInTouch})}
